# Generated by Django 5.1.15 on 2026-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Компания')),
                ('plan', models.CharField(choices=[('base', 'Базовый'), ('extended', 'Расширенный'), ('vip', 'VIP / Сопровождение'), ('other', 'Другое / не выбрано')], default='other', max_length=20, verbose_name='Формат')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
