# Generated by Django 5.2.15 on 2026-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('chart', 'Столбчатый график'), ('growth', 'Рост / тренд'), ('tax', 'Документ / налоги'), ('audit', 'Лупа / аудит'), ('briefcase', 'Портфель'), ('users', 'Люди / сопровождение')], default='chart', help_text='Какой SVG показать в карточке услуги', max_length=30, verbose_name='Иконка (SVG)'),
        ),
    ]
